#!/bin/bash

# BTC Tech Mail Server - API Test Suite
# This script tests: Login, Send Mail, Get Inbox, Star Mail, and Get Starred Mails.

BASE_URL="http://localhost:8080"
SENDER_EMAIL="hari@bnxgmail.com"
RECEIVER_EMAIL="ashanmugavel821@gmail.com"
PASSWORD="SecurePassword123" # Adjust if necessary

echo "------------------------------------------------"
echo "Starting BTC Tech Mail API Test Suite"
echo "------------------------------------------------"

# 1. LOGIN SENDER
echo "[1/5] Logging in as Sender ($SENDER_EMAIL)..."
SENDER_RESPONSE=$(curl -s -X POST "$BASE_URL/api/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\": \"$SENDER_EMAIL\", \"password\": \"$PASSWORD\"}")

SENDER_TOKEN=$(echo $SENDER_RESPONSE | jq -r '.data.accessToken')

if [ "$SENDER_TOKEN" == "null" ] || [ -z "$SENDER_TOKEN" ]; then
  echo "❌ Login failed for $SENDER_EMAIL. Response: $SENDER_RESPONSE"
  exit 1
fi
echo "✅ Login successful. Token obtained."

# 2. SEND EMAIL
echo "[2/5] Sending email from $SENDER_EMAIL to $RECEIVER_EMAIL..."
SEND_RESPONSE=$(curl -s -X POST "$BASE_URL/api/mail/send" \
  -H "Authorization: Bearer $SENDER_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"to\": \"$RECEIVER_EMAIL\",
    \"subject\": \"Test Mail from Terminal\",
    \"body\": \"This is a test message generated by the terminal test script.\",
    \"isHtml\": false
  }")

if [[ $SEND_RESPONSE == *"\"success\":true"* ]]; then
  echo "✅ Email sent successfully."
else
  echo "❌ Failed to send email. Response: $SEND_RESPONSE"
  exit 1
fi

# 3. LOGIN RECEIVER
echo "[3/5] Logging in as Receiver ($RECEIVER_EMAIL)..."
RECEIVER_RESPONSE=$(curl -s -X POST "$BASE_URL/api/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\": \"$RECEIVER_EMAIL\", \"password\": \"$PASSWORD\"}")

RECEIVER_TOKEN=$(echo $RECEIVER_RESPONSE | jq -r '.data.accessToken')

if [ "$RECEIVER_TOKEN" == "null" ] || [ -z "$RECEIVER_TOKEN" ]; then
  echo "❌ Login failed for $RECEIVER_EMAIL. Response: $RECEIVER_RESPONSE"
  exit 1
fi
echo "✅ Login successful."

# 4. GET INBOX & STAR THE EMAIL
echo "[4/5] Fetching inbox for $RECEIVER_EMAIL..."
INBOX_RESPONSE=$(curl -s -X GET "$BASE_URL/api/mail/inbox?limit=1" \
  -H "Authorization: Bearer $RECEIVER_TOKEN")

# Get UID of the latest email
LATEST_UID=$(echo $INBOX_RESPONSE | jq -r '.data.emails[0].uid')

if [ "$LATEST_UID" == "null" ] || [ -z "$LATEST_UID" ]; then
  echo "❌ No emails found in inbox. Response: $INBOX_RESPONSE"
  exit 1
fi

echo "⭐ Starring email with UID: $LATEST_UID..."
STAR_RESPONSE=$(curl -s -X POST "$BASE_URL/api/mail/star/$LATEST_UID" \
  -H "Authorization: Bearer $RECEIVER_TOKEN")

if [[ $STAR_RESPONSE == *"\"success\":true"* ]]; then
  echo "✅ Email starred successfully."
else
  echo "❌ Failed to star email. Response: $STAR_RESPONSE"
  exit 1
fi

# 5. GET STARRED EMAILS
echo "[5/5] Fetching starred emails for $RECEIVER_EMAIL..."
STARRED_RESPONSE=$(curl -s -X GET "$BASE_URL/api/mail/starred" \
  -H "Authorization: Bearer $RECEIVER_TOKEN")

STARRED_COUNT=$(echo $STARRED_RESPONSE | jq -r '.data.totalCount')

if [ "$STARRED_COUNT" -gt 0 ]; then
  echo "✅ Found $STARRED_COUNT starred email(s)."
  echo "------------------------------------------------"
  echo "TEST SUITE PASSED SUCCESSFULLY"
  echo "------------------------------------------------"
else
  echo "❌ Starred email not found in starred list. Response: $STARRED_RESPONSE"
  exit 1
fi
