package com.btctech.mailapp.config;

import com.btctech.mailapp.entity.Domain;
import com.btctech.mailapp.entity.MailAccount;
import com.btctech.mailapp.entity.User;
import com.btctech.mailapp.entity.AccountType;
import com.btctech.mailapp.repository.DomainRepository;
import com.btctech.mailapp.repository.MailAccountRepository;
import com.btctech.mailapp.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Component
@RequiredArgsConstructor
public class AdminSeeder implements CommandLineRunner {

    private final UserRepository userRepository;
    private final MailAccountRepository mailAccountRepository;
    private final DomainRepository domainRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        String adminEmail = "admin@bnxmail.com";
        String adminPassword = "1234";

        // 1. Ensure domain exists
        Domain domain = domainRepository.findByDomain("bnxmail.com")
                .orElseGet(() -> {
                    Domain newDomain = new Domain();
                    newDomain.setDomain("bnxmail.com");
                    newDomain.setActive(true);
                    return domainRepository.save(newDomain);
                });

        if (!userRepository.existsByUsername(adminEmail)) {
            log.info("Seeding default Admin user: {}", adminEmail);

        // 2. Create User
        User admin = new User();
        admin.setUsername(adminEmail);
        admin.setEmail(adminEmail);
        admin.setPassword(passwordEncoder.encode(adminPassword));
        admin.setFirstName("Super");
        admin.setLastName("Admin");
        admin.setRole("ADMIN"); // Ensure they have the ADMIN role
        admin.setAccountType(AccountType.PUBLIC);
        admin.setActive(true);
        admin.setApproved(true);
        admin = userRepository.save(admin);

        // 3. Create MailAccount
        MailAccount mailAccount = new MailAccount();
        mailAccount.setUserId(admin.getId());
        mailAccount.setDomainId(domain.getId());
        mailAccount.setEmailName("admin");
        mailAccount.setEmail(adminEmail);
        mailAccount.setMaildirPath(adminEmail);
        mailAccount.setIsPrimary(true);
        mailAccount.setQuota(10L * 1024 * 1024 * 1024); // 10GB for admin
        
        // Use the MailboxService to hash the password properly for Dovecot
        String dovecotHash = "{BLF-CRYPT}" + passwordEncoder.encode(adminPassword);
        mailAccount.setPassword(dovecotHash);
        mailAccount.setEncryptedPassword(dovecotHash);
        mailAccount = mailAccountRepository.save(mailAccount);

            // Folders will be auto-generated by Dovecot upon first IMAP login if needed

            log.info("Successfully seeded Admin user! You can now login with {} and password 1234", adminEmail);
        } else {
            log.info("Admin user already exists. Skipping admin seeding.");
        }

        // --- Seed Calendar Account ---
        String calendarEmail = "calendar@bnxmail.com";
        String calendarPassword = "secure-calendar-1234";

        if (!userRepository.existsByUsername(calendarEmail)) {
            log.info("Seeding Calendar user: {}", calendarEmail);
            
            User calendarUser = new User();
            calendarUser.setUsername(calendarEmail);
            calendarUser.setEmail(calendarEmail);
            calendarUser.setPassword(passwordEncoder.encode(calendarPassword));
            calendarUser.setFirstName("Calendar");
            calendarUser.setLastName("App");
            calendarUser.setRole("USER");
            calendarUser.setAccountType(AccountType.PUBLIC);
            calendarUser.setActive(true);
            calendarUser.setApproved(true);
            calendarUser = userRepository.save(calendarUser);

            MailAccount calMailAccount = new MailAccount();
            calMailAccount.setUserId(calendarUser.getId());
            calMailAccount.setDomainId(domain.getId());
            calMailAccount.setEmailName("calendar");
            calMailAccount.setEmail(calendarEmail);
            calMailAccount.setMaildirPath(calendarEmail);
            calMailAccount.setIsPrimary(true);
            calMailAccount.setQuota(2L * 1024 * 1024 * 1024); // 2GB

            String calDovecotHash = "{BLF-CRYPT}" + passwordEncoder.encode(calendarPassword);
            calMailAccount.setPassword(calDovecotHash);
            calMailAccount.setEncryptedPassword(calDovecotHash);
            mailAccountRepository.save(calMailAccount);

            log.info("Successfully seeded Calendar user!");
        }
    }
}
